// apps/e-learning/src/frontend/components/layout/secondary-navbar.svelte
<script lang="ts">
	export let title: string = 'E-Learning';
	export let href: string = '/';
</script>

<div
	class="sticky top-0 z-50 w-full border-b border-gray-200 bg-white font-sans text-[#081f5c] shadow-sm"
>
	<div
		class="mx-auto flex max-w-7xl items-center gap-4 px-4 py-4 md:gap-6 md:px-8 md:py-6 lg:px-16"
	>
		<a
			{href}
			class="group flex cursor-pointer items-center gap-2 font-medium text-gray-600 transition-opacity hover:opacity-80"
		>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				width="24"
				height="24"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				stroke-linecap="round"
				stroke-linejoin="round"
				class="h-5 w-5 transition-transform duration-300 group-hover:-translate-x-1"
			>
				<path d="m12 19-7-7 7-7" />
				<path d="M19 12H5" />
			</svg>
			<span class="hidden sm:inline">Back to Home</span>
			<span class="sm:hidden">Back</span>
		</a>
		<div class="h-6 w-px bg-gray-300"></div>
		<h1 class="truncate text-xl font-bold text-[#081f5c] capitalize md:text-2xl">
			{title}
		</h1>
	</div>
</div>

// apps/home/app/components/layout/secondary-navbar.tsx
import { ArrowLeft } from "lucide-react";
import Link from "next/link";

interface SecondaryNavbarProps {
  title: string;
  href?: string;
}

export function SecondaryNavbar({ title, href = "/" }: SecondaryNavbarProps) {
  return (
    <div className="w-full bg-white text-[#081f5c] sticky top-0 z-50 border-b border-gray-200 shadow-sm">
      <div className="max-w-7xl mx-auto px-4 md:px-8 lg:px-16 py-4 md:py-6 flex items-center gap-4 md:gap-6">
        <Link
          href={href}
          className="group flex items-center gap-2 hover:opacity-80 transition-opacity text-gray-600 font-medium cursor-pointer"
        >
          <ArrowLeft className="w-5 h-5 transition-transform duration-300 group-hover:-translate-x-1" />
          <span className="hidden sm:inline">Back to Home</span>
          <span className="sm:hidden">Back</span>
        </Link>
        <div className="h-6 w-px bg-gray-300"></div>
        <h1 className="text-xl md:text-2xl font-bold capitalize text-[#081f5c] truncate">
          {title}
        </h1>
      </div>
    </div>
  );
}
